### ISSUE TITLE
Desenvolver Modelo ER

### ISSUE THREAD

**Issue by FabioBeneditto** [LazyParking/lazyparking-documentation#16]
Desenvolver o Modelo ER dos bancos de dados: 
- [x] Paulo faz do MongoDB (Backend)
- ~~[ ] Fabio faz do MySQL (Frontend)~~

**Comment by paulodiovani** [comment]
Criei um Diagrama de Objetos, que deve substituir o ER.
https://docs.google.com/a/diovani.com/drawings/d/1mP1j4DoQTaqmmv2hr_1yIKPgkQ0x2YVze_TF3tlsoug/edit

**Comment by paulodiovani** [comment]
Adicionei os Managers no diagrama.

Inicialmente pensava em manter uma base auxiliar para autenticação e relatórios. Estou achando que não será necessário -- podemos deixar tudo no serviço.

Que acha @FabioBeneditto ?

**Comment by FabioBeneditto** [comment]
Acho que podemos POR ENQUANTO gerenciar pelo backend. Se surgir necessidade, mudamos. Filosofia KISS

**Comment by paulodiovani** [comment]
Certo. Então vou marcar este issue como concluído.
