### ISSUE TITLE
Revisar documentos entregues e validar pendências

### ISSUE THREAD

**Issue by paulodiovani** [LazyParking/lazyparking-documentation#22]
Os documentos que foram entregues precisam de revisão, para ver se estão de acordo com o que definimos nas últimas reuniões.

Além disso é necessário escrever os UCs que faltam.
- [x] Conferir e, se necessário, atualizar UCs entregues
- [x] Escrever os UCs que faltam
- [x] Atualizar diagrama de domínio
- [x] Atualizar diagrama de objetos
- [x] Atualizar documento de visão

**Comment by FabioBeneditto** [comment]
Já encerrado!
